(asdf:defsystem "claw-lisp"
  :description "Standalone provider-neutral coding agent runtime in Common Lisp."
  :author "seyiakadri@gmail.com"
  :license "BSL-1.1 (see LICENSE)"
  :version "0.1.0"
  :serial t
  :depends-on ("uiop" "dexador" "yason" "ironclad")
  :components
  ((:file "lisp/packages")
   (:file "lisp/config")
   (:file "lisp/core/domain")
   (:file "lisp/core/token-estimation")
   (:file "lisp/core/context-monitor")
   (:file "lisp/core/protocols")
   (:file "lisp/providers/http-json")
   (:file "lisp/storage/transcripts")
   (:file "lisp/storage/tool-results")
   (:file "lisp/storage/cas")
   (:file "lisp/storage/cas-ref-store")
   (:file "lisp/cas/crypto")
   (:file "lisp/cas/manifest")
   (:file "lisp/cas/integrity")
   (:file "lisp/core/artifacts")
   (:file "lisp/ir/conditions")
   (:file "lisp/ir/schema")
   (:file "lisp/ir/cas-bridge")
   (:file "lisp/ir/validate")
   (:file "lisp/ir/expander")
   (:file "lisp/ir/semantic")
   (:file "lisp/ir/prepare")
   (:file "lisp/ir/execution-plan")
   (:file "lisp/ir/surface-form")
   (:file "lisp/ir/optimize")
   (:file "lisp/storage/session-memory")
   (:file "lisp/storage/durable-memory")
   (:file "lisp/providers/embeddings")
   (:file "lisp/providers/openai-embeddings")
   (:file "lisp/storage/durable-memory-embeddings")
   (:file "lisp/storage/durable-memory-search")
   (:file "lisp/storage/durable-memory-query")
   (:file "lisp/storage/consolidation-lock")
   (:file "lisp/core/microcompact")
   (:file "lisp/core/model-registry")
   (:file "lisp/core/compact")
   (:file "lisp/core/conditions")
   (:file "lisp/core/phases")
   (:file "lisp/core/completion")
   (:file "lisp/core/tool-envelope")
   (:file "lisp/core/claude-md")
   (:file "lisp/core/system-prompt")
   (:file "lisp/providers/rate-limit")
   (:file "lisp/providers/retry")
   (:file "lisp/providers/auth")
   (:file "lisp/providers/sse-parser")
   (:file "lisp/providers/http-utils")
   (:file "lisp/providers/stream-accumulator")
   (:file "lisp/core/message-normalization")
   (:file "lisp/core/agent-mailbox-stub")
   (:file "lisp/core/agent-supervisor-stub")
   (:file "lisp/core/runtime")
   (:file "lisp/ir/local-execution")
   (:file "lisp/tools/echo")
   (:file "lisp/tools/file-read")
   (:file "lisp/tools/file-write")
   (:file "lisp/tools/file-replace")
   (:file "lisp/tools/glob")
   (:file "lisp/tools/grep")
   (:file "lisp/tools/shell-command")
   (:file "lisp/core/tool-phases")
   (:file "lisp/core/phase-progression")
   (:file "lisp/providers/bedrock")
   (:file "lisp/providers/anthropic")
   (:file "lisp/providers/openrouter")
   (:file "lisp/providers/mock")))

(asdf:defsystem "claw-lisp/test"
  :description "Tests for the standalone claw-lisp runtime."
  :author "seyiakadri@gmail.com"
  :license "BSL-1.1 (see LICENSE)"
  :version "0.1.0"
  :depends-on ("claw-lisp-cli" "fiveam")
  :serial t
  :components
  ((:file "lisp/tests/runtime")
   (:file "lisp/tests/token-estimation")
   (:file "lisp/tests/context-monitor")
   (:file "lisp/tests/runtime-context")
   (:file "lisp/tests/phase4-integration")
   (:file "lisp/tests/session-memory-test")
   (:file "lisp/tests/durable-memory-scoring-test")
   (:file "lisp/tests/durable-memory-test")
   (:file "lisp/tests/durable-memory-query-test")
   (:file "lisp/tests/durable-memory-runtime-integration-test")
   (:file "lisp/tests/phase7-e2e-fixtures")
   (:file "lisp/tests/phase7-e2e-conversation-tests")
   (:file "lisp/tests/phase7-e2e-circuit-breaker-tests")
   (:file "lisp/tests/phase7-e2e-consolidation-tests")
   (:file "lisp/tests/phase7-e2e-multi-session-tests")
   (:file "lisp/tests/phase7-e2e-performance-tests")
   (:file "lisp/tests/durable-memory-e2e")
   (:file "lisp/tests/test-search")
   ;; NOTE: lisp/tests/normalization-real is intentionally NOT registered.
   ;; As of 2026-04-21 the file is an unfinished harness: it references an
   ;; unbound symbol `tool-results` (line 131) and is not callable. Finish
   ;; the harness and add it back here before relying on it.
   (:file "lisp/tests/rate-limit")
   (:file "lisp/tests/cas-test")
   (:file "lisp/tests/phases-test")
   (:file "lisp/tests/completion-test")
   (:file "lisp/tests/tool-envelope-test")
   (:file "lisp/tests/tool-phases-test")
   (:file "lisp/tests/phase-progression-test")
   (:file "lisp/tests/prf-001-regression-test")
   (:file "lisp/tests/cas-ref-store")
   (:file "lisp/tests/cas-manifest")
   (:file "lisp/tests/cas-integrity")
   (:file "lisp/tests/artifacts")
   (:file "lisp/tests/ir")))
